### ISSUE TITLE
java 8/win 10 build fails because of findbugs error

### ISSUE THREAD

**Issue by jjYBdx4IL** [fluxroot/jcpi#106]
19:49:46.776 [ERROR] [org.gradle.BuildExceptionReporter]
19:49:46.784 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
19:49:46.797 [ERROR] [org.gradle.BuildExceptionReporter]
19:49:46.806 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
19:49:46.814 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':findbugsIntegration'.
19:49:46.824 [ERROR] [org.gradle.BuildExceptionReporter] > FindBugs encountered an error. Run with --debug to get more information.
19:49:46.850 [ERROR] [org.gradle.BuildExceptionReporter]
19:49:46.858 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
19:49:46.868 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':findbugsIntegration'.
19:49:46.885 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
19:49:46.906 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
19:49:46.923 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
19:49:46.940 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
19:49:46.956 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
19:49:46.973 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
19:49:46.990 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
19:49:47.004 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
19:49:47.023 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
19:49:47.040 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:283)
19:49:47.052 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
19:49:47.074 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
19:49:47.088 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
19:49:47.104 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$1.run(DefaultTaskPlanExecutor.java:33)
19:49:47.120 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Factories$1.create(Factories.java:22)
19:49:47.130 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultCacheAccess.longRunningOperation(DefaultCacheAccess.java:214)
19:49:47.143 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultCacheAccess.longRunningOperation(DefaultCacheAccess.java:276)
19:49:47.156 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.longRunningOperation(DefaultPersistentDirectoryStore.java:142)
19:49:47.174 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.changedetection.state.DefaultTaskArtifactStateCacheAccess.longRunningOperation(DefaultTaskArtifactStateCacheAccess.java:78)
19:49:47.188 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:31)
19:49:47.205 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:86)
19:49:47.224 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
19:49:47.237 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
19:49:47.250 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
19:49:47.268 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:67)
19:49:47.284 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
19:49:47.301 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
19:49:47.319 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:54)
19:49:47.333 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:166)
19:49:47.353 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:113)
19:49:47.367 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:81)
19:49:47.384 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:64)
19:49:47.408 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
19:49:47.420 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
19:49:47.433 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:35)
19:49:47.458 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
19:49:47.474 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
19:49:47.485 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
19:49:47.501 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:201)
19:49:47.524 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:174)
19:49:47.541 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:170)
19:49:47.558 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:139)
19:49:47.574 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
19:49:47.587 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
19:49:47.602 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:46)
19:49:47.616 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
19:49:47.626 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.main(Main.java:37)
19:49:47.634 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:50)
19:49:47.651 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:32)
19:49:47.668 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
19:49:47.685 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
19:49:47.702 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
19:49:47.718 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:58)
19:49:47.734 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.GradleException: FindBugs encountered an error. Run with --debug to get more information.
19:49:47.758 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.plugins.quality.FindBugs.evaluateResult(FindBugs.groovy:211)
19:49:47.771 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.plugins.quality.FindBugs.run(FindBugs.groovy:180)
19:49:47.784 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.JavaMethod.invoke(JavaMethod.java:62)
19:49:47.800 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:219)
19:49:47.813 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:212)
19:49:47.833 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:201)
19:49:47.859 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:527)
19:49:47.871 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:510)
19:49:47.884 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
19:49:47.897 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
19:49:47.915 [ERROR] [org.gradle.BuildExceptionReporter]        ... 52 more
19:49:47.933 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.ArrayIndexOutOfBoundsException: 7352
19:49:47.950 [ERROR] [org.gradle.BuildExceptionReporter]        at org.objectweb.asm.ClassReader.readClass(Unknown Source)
19:49:47.960 [ERROR] [org.gradle.BuildExceptionReporter]        at org.objectweb.asm.ClassReader.accept(Unknown Source)
19:49:47.969 [ERROR] [org.gradle.BuildExceptionReporter]        at edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
19:49:47.984 [ERROR] [org.gradle.BuildExceptionReporter]        at org.objectweb.asm.ClassReader.accept(Unknown Source)
19:49:47.993 [ERROR] [org.gradle.BuildExceptionReporter]        at edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
19:49:48.004 [ERROR] [org.gradle.BuildExceptionReporter]        at edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:554)
19:49:48.020 [ERROR] [org.gradle.BuildExceptionReporter]        at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
19:49:48.042 [ERROR] [org.gradle.BuildExceptionReporter]        at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
19:49:48.059 [ERROR] [org.gradle.BuildExceptionReporter]        at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:266)
19:49:48.072 [ERROR] [org.gradle.BuildExceptionReporter]        at edu.umd.cs.findbugs.ba.npe.TypeQualifierNullnessAnnotationDatabase.getXMethod(TypeQualifierNullnessAnnotationDatabase.java:293)
19:49:48.092 [ERROR] [org.gradle.BuildExceptionReporter]        at edu.umd.cs.findbugs.ba.npe.TypeQualifierNullnessAnnotationDatabase.addMethodParameterAnnotation(TypeQualifierNullnessAnnotationDatabase.java:355)
19:49:48.108 [ERROR] [org.gradle.BuildExceptionReporter]        at edu.umd.cs.findbugs.ba.DefaultNullnessAnnotations.addDefaultNullnessAnnotations(DefaultNullnessAnnotations.java:63)
19:49:48.125 [ERROR] [org.gradle.BuildExceptionReporter]        at edu.umd.cs.findbugs.ba.npe.TypeQualifierNullnessAnnotationDatabase.loadAuxiliaryAnnotations(TypeQualifierNullnessAnnotationDatabase.java:390)
19:49:48.142 [ERROR] [org.gradle.BuildExceptionReporter]        at edu.umd.cs.findbugs.ba.AnalysisCacheToAnalysisContextAdapter.updateDatabases(AnalysisCacheToAnalysisContextAdapter.java:420)
19:49:48.159 [ERROR] [org.gradle.BuildExceptionReporter]        at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1142)
19:49:48.175 [ERROR] [org.gradle.BuildExceptionReporter]        at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:279)
19:49:48.185 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.plugins.quality.internal.findbugs.FindBugsExecuter.runFindbugs(FindBugsExecuter.java:44)
19:49:48.209 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.plugins.quality.internal.findbugs.FindBugsWorkerServer.execute(FindBugsWorkerServer.java:44)
19:49:48.226 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.plugins.quality.internal.findbugs.FindBugsWorkerServer.execute(FindBugsWorkerServer.java:35)
19:49:48.243 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.plugins.quality.internal.findbugs.FindBugsWorkerServer.execute(FindBugsWorkerServer.java:26)
19:49:48.260 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:78)
19:49:48.273 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:35)
19:49:48.288 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.child.ImplementationClassLoaderWorker.execute(ImplementationClassLoaderWorker.java:85)
19:49:48.310 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.child.ImplementationClassLoaderWorker.execute(ImplementationClassLoaderWorker.java:41)
19:49:48.326 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.child.IsolatedApplicationClassLoaderWorker.call(IsolatedApplicationClassLoaderWorker.java:48)
19:49:48.343 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.child.IsolatedApplicationClassLoaderWorker.call(IsolatedApplicationClassLoaderWorker.java:30)
19:49:48.360 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.launcher.GradleWorkerMain.run(GradleWorkerMain.java:32)
19:49:48.372 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.launcher.GradleWorkerMain.main(GradleWorkerMain.java:37)
19:49:48.387 [ERROR] [org.gradle.BuildExceptionReporter]
19:49:48.399 [LIFECYCLE] [org.gradle.BuildResultLogger]
19:49:48.406 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
19:49:48.414 [LIFECYCLE] [org.gradle.BuildResultLogger]
19:49:48.422 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 1 mins 12.061 secs

**Comment by jjYBdx4IL** [comment]
gradle wrapper used an old gradle version
